Updated linting workflow

diff --git a/.github/workflows/PR-Helm-Check.yml b/.github/workflows/PR-Helm-Check.yml
--- a/.github/workflows/PR-Helm-Check.yml
+++ b/.github/workflows/PR-Helm-Check.yml
@@ -16,50 +16,56 @@ jobs:
         working-directory: charts
         run: |
           lint_regex="\[(.*)\] ([^ ]*): (.*)"
-          for path in ./* ; do
-            template=""
-            linted=""
-            if [ -f "$path/test.values.yaml" ]; then
-                linted=$(helm lint "$path" --values "$path/test.values.yaml")
-                template=$(helm template "$path" -n test --name-template=template-test -f "$path/test.values.yaml" --debug | tr '\n' ' \\n')
-            else
-                linted=$(helm lint "$path")
-                template=$(helm template "$path" -n test --name-template=template-test --debug | tr '\n' ' \\n')
-            fi
-            echo "::group::$path"
-            while read linted ; do
-                if [[ $linted =~ $lint_regex ]]; then
-                    level="${BASH_REMATCH[1]}"
-                    file="${path}${BASH_REMATCH[2]}"
-                    message="${BASH_REMATCH[3]}"
-                    if [ $level = "ERROR" ]  
-                    then
-                        echo "::error file=${file}::${message}"
-                    elif [ $level = "WARNING" ]
-                    then
-                        echo "::warning file=${file}::${message}"
-                    else
-                        echo "::notice file=${file}::${message}"
-                    fi
-                fi
-                echo "$t" >&2
+          for path in charts/* ; do
+              [[ -f "$path/Chart.yaml" ]] || continue;
+
+              echo "::group::$path"
+
+              template=""
+              linted=""
+              if [ -f "$path/test.values.yaml" ]; then
+                  linted=$(helm lint "$path" --values "$path/test.values.yaml")
+                  template=$(helm template "$path" -n test --name-template=template-test -f "$path/test.values.yaml" | tr '\n' ' \\n')
+              else
+                  linted=$(helm lint "$path")
+                  template=$(helm template "$path" -n test --name-template=template-test | tr '\n' ' \\n')
+              fi
+
+              while read linted ; do
+                  if [[ $linted =~ $lint_regex ]]; then
+                      level="${BASH_REMATCH[1]}"
+                      file="${path}${BASH_REMATCH[2]}"
+                      message="${BASH_REMATCH[3]}"
+                      if [ $level = "ERROR" ]  
+                      then
+                          echo "::error file=${file}::${message}"
+                      elif [ $level = "WARNING" ]
+                      then
+                          echo "::warning file=${file}::${message}"
+                      else
+                          echo "::notice file=${file}::${message}"
+                      fi
+                  fi
+                  echo "$t" >&2
               done
-            while read template ; do
-                if [[ $template =~ $lint_regex ]]; then
-                    level="${BASH_REMATCH[1]}"
-                    file="${path}${BASH_REMATCH[2]}"
-                    message="${BASH_REMATCH[3]}"
-                    if [ $level = "ERROR" ]  
-                    then
-                        echo "::error file=${file}::${message}"
-                    elif [ $level = "WARNING" ]
-                    then
-                        echo "::warning file=${file}::${message}"
-                    else
-                        echo "::notice file=${file}::${message}"
-                    fi
-                fi
-                echo "$t" >&2
+              
+              while read template ; do
+                  if [[ $template =~ $lint_regex ]]; then
+                      level="${BASH_REMATCH[1]}"
+                      file="${path}${BASH_REMATCH[2]}"
+                      message="${BASH_REMATCH[3]}"
+                      if [ $level = "ERROR" ]  
+                      then
+                          echo "::error file=${file}::${message}"
+                      elif [ $level = "WARNING" ]
+                      then
+                          echo "::warning file=${file}::${message}"
+                      else
+                          echo "::notice file=${file}::${message}"
+                      fi
+                  fi
+                  echo "$t" >&2
               done
-            echo "::endgroup::"
+
+              echo "::endgroup::"
           done
